name: Build Documentation
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Reference
        run: |
          mvn -B site --file pom.xml
      - name: Build Documentation
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}.
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
