name: Java CI

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: debug
        run: echo ${GITHUB_REF:10}
      - name: Prepare files
        run: sed -i "s/CyanIsAFurry/${GITHUB_REF:10}/g" src/main/kotlin/beatwalls/Update.kt
      - name: Prepare pom
        run: sed -i "s/<version>0.0.0.0<\/version>/<version>${GITHUB_REF:11}.0<\/version>/g" pom.xml
      - name: Set up JDK 1.8
        uses: actions/setup-java@master
        with:
          java-version: 1.8
      - name: Build with Maven
        run: cat src/main/kotlin/beatwalls/Update.kt && mvn -B package --file pom.xml
      - name: create Documentation with maven
        run: mvn -B site --file pom.xml
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: 👻BeatWalls ${{ github.ref }}👻
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/beatwalls/beatwalls/target/Beatwalls.exe
          asset_name: beatwalls.exe
          asset_content_type: application/exe

